# Generated by Django 5.2.8 on 2025-12-13 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_and_more"),
        ("projects", "0001_initial"),
        ("stores", "0002_store_stores_stor_company_924203_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company", "name"], name="projects_pr_company_703d94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["store"], name="projects_pr_store_i_f10f4b_idx"),
        ),
    ]
