# Generated by Django 5.2.8 on 2025-11-18 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('gondola', 'Gondola'), ('endcap', 'Endcap'), ('wall_unit', 'Wall Unit'), ('refrigerated_case', 'Refrigerated Case'), ('freezer_case', 'Freezer Case'), ('island_display', 'Island Display'), ('checkout_counter', 'Checkout Counter'), ('shelf', 'Shelf'), ('rack', 'Rack'), ('bin', 'Bin'), ('other', 'Other')], max_length=50)),
                ('width_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shelf_count', models.IntegerField()),
                ('shelf_spacing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_category', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='custom', help_text='Standard displays are available to all companies, custom displays are company-specific', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null for standard displays, set for custom displays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_displays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='displays_di_company_8d40f5_idx'), models.Index(fields=['display_category'], name='displays_di_display_0c9e6c_idx')],
            },
        ),
    ]
