# Generated by Django 5.2.8 on 2025-11-19 01:33

from django.db import migrations


def add_display_category_column_if_missing(apps, schema_editor):
    """Add display_category column if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='displays_display' AND column_name='display_category'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE displays_display 
                ADD COLUMN display_category VARCHAR(20) DEFAULT 'custom' 
                NOT NULL
            """)
            # Update existing rows: standard if company is null, custom otherwise
            cursor.execute("""
                UPDATE displays_display 
                SET display_category = CASE 
                    WHEN company_id IS NULL THEN 'standard' 
                    ELSE 'custom' 
                END
            """)
            # Create index
            try:
                cursor.execute("""
                    CREATE INDEX displays_di_display_0c9e6c_idx 
                    ON displays_display(display_category)
                """)
            except Exception:
                # Index might already exist, ignore
                pass


def remove_display_category_column(apps, schema_editor):
    """Remove display_category column if migration is reversed"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DROP INDEX IF EXISTS displays_di_display_0c9e6c_idx
        """)
        cursor.execute("""
            ALTER TABLE displays_display 
            DROP COLUMN IF EXISTS display_category
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_display_category_column_if_missing,
            reverse_code=remove_display_category_column,
        ),
    ]
