# Generated by Django 5.2.8 on 2025-11-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Standard display templates available to all companies'),
        ),
        migrations.AlterField(
            model_name='display',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='accounts.company'),
        ),
    ]
