# Generated by Django 5.2.8 on 2025-11-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_standard_displays_to_display(apps, schema_editor):
    """Migrate StandardDisplay data to Display with company=null"""
    StandardDisplay = apps.get_model('displays', 'StandardDisplay')
    Display = apps.get_model('displays', 'Display')
    
    # Migrate all StandardDisplay records to Display with company=null
    for standard in StandardDisplay.objects.all():
        Display.objects.get_or_create(
            name=standard.name,
            company=None,
            defaults={
                'type': standard.type,
                'width_in': standard.width_in,
                'height_in': standard.height_in,
                'depth_in': standard.depth_in,
                'shelf_count': standard.shelf_count,
                'shelf_spacing': standard.shelf_spacing,
                'is_archived': False,
            }
        )


def reverse_migration(apps, schema_editor):
    """Reverse migration - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('displays', '0003_auto_20251114_1628'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, ensure company field is nullable (it should already be from migration 0002, but ensure it)
        migrations.AlterField(
            model_name='display',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for standard displays, set for company-specific displays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='accounts.company'),
        ),
        # Then migrate StandardDisplay data to Display
        migrations.RunPython(migrate_standard_displays_to_display, reverse_migration),
        # Then delete StandardDisplay model
        migrations.DeleteModel(
            name='StandardDisplay',
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['company', 'is_archived'], name='displays_di_company_e4e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['company'], name='displays_di_company_8d40f5_idx'),
        ),
    ]
