# Generated by Django 5.2.8 on 2025-11-19 01:40

from django.db import migrations


def create_standard_displays(apps, schema_editor):
    """Create the 6 standard displays from the SQLite database"""
    Display = apps.get_model('displays', 'Display')
    
    standard_displays = [
        {
            'name': '5-Foot Wall Mounted Display Shelf',
            'type': 'shelf',
            'width_in': 60,
            'height_in': 60,
            'depth_in': 18,
            'shelf_count': 4,
            'display_category': 'standard',
            'company': None,
        },
        {
            'name': '5-Foot Freestanding Storage Shelf',
            'type': 'shelf',
            'width_in': 60,
            'height_in': 72,
            'depth_in': 18,
            'shelf_count': 5,
            'display_category': 'standard',
            'company': None,
        },
        {
            'name': '6-Foot Gondola Back Shelf Unit',
            'type': 'shelf',
            'width_in': 72,
            'height_in': 60,
            'depth_in': 18,
            'shelf_count': 4,
            'display_category': 'standard',
            'company': None,
        },
        {
            'name': '6-Foot Merchandising Display Shelf',
            'type': 'shelf',
            'width_in': 72,
            'height_in': 84,
            'depth_in': 18,
            'shelf_count': 6,
            'display_category': 'standard',
            'company': None,
        },
        {
            'name': '7-Foot Endcap Display Shelf',
            'type': 'shelf',
            'width_in': 84,
            'height_in': 72,
            'depth_in': 18,
            'shelf_count': 5,
            'display_category': 'standard',
            'company': None,
        },
        {
            'name': '8-Foot Wall Unit Display Shelf',
            'type': 'shelf',
            'width_in': 96,
            'height_in': 84,
            'depth_in': 18,
            'shelf_count': 6,
            'display_category': 'standard',
            'company': None,
        },
    ]
    
    for display_data in standard_displays:
        Display.objects.get_or_create(
            name=display_data['name'],
            defaults=display_data
        )


def remove_standard_displays(apps, schema_editor):
    """Remove the standard displays (reverse migration)"""
    Display = apps.get_model('displays', 'Display')
    Display.objects.filter(display_category='standard', company__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0003_remove_is_archived_column'),
    ]

    operations = [
        migrations.RunPython(
            create_standard_displays,
            reverse_code=remove_standard_displays,
        ),
    ]
