# Generated by Django 5.2.8 on 2025-11-19 01:46

from django.db import migrations


def remove_standarddisplay_table(apps, schema_editor):
    """Remove the displays_standarddisplay table if it exists (legacy table)"""
    db_alias = schema_editor.connection.alias
    db_vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        # Check if table exists (database-agnostic)
        table_exists = False

        if db_vendor == 'sqlite':
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='table' AND name='displays_standarddisplay'
            """)
            table_exists = cursor.fetchone() is not None
        else:  # PostgreSQL
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'displays_standarddisplay'
            """)
            table_exists = cursor.fetchone() is not None

        if table_exists:
            if db_vendor == 'sqlite':
                cursor.execute("DROP TABLE IF EXISTS displays_standarddisplay")
            else:
                cursor.execute("DROP TABLE IF EXISTS displays_standarddisplay CASCADE")


def add_standarddisplay_table(apps, schema_editor):
    """Reverse migration - recreate the table (if needed)"""
    # We don't know the original structure, so we'll skip reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0004_create_standard_displays'),
    ]

    operations = [
        migrations.RunPython(
            remove_standarddisplay_table,
            reverse_code=add_standarddisplay_table,
        ),
    ]
