# Generated by Django 5.2.8 on 2025-12-28 14:29

from decimal import Decimal
from django.db import migrations, models


def populate_null_shelf_spacing(apps, schema_editor):
    """Populate NULL shelf_spacing values with default before making field non-nullable."""
    Display = apps.get_model('displays', 'Display')

    # Update all displays with NULL shelf_spacing to default value
    Display.objects.filter(shelf_spacing__isnull=True).update(
        shelf_spacing=Decimal("12.00")
    )


def reverse_population(apps, schema_editor):
    """Reverse migration - no-op since we can't know which values were NULL."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0005_remove_standarddisplay_table'),
    ]

    operations = [
        # Step 1: Populate NULL values with default
        migrations.RunPython(populate_null_shelf_spacing, reverse_population),

        # Step 2: Alter field to add default and make non-nullable
        migrations.AlterField(
            model_name='display',
            name='shelf_spacing',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Vertical spacing between shelves in inches', max_digits=10),
        ),
    ]
