# Generated by Django 5.2.8 on 2025-11-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_display_category_and_clean_names(apps, schema_editor):
    """Set display_category based on company and remove 'Standard' prefix from names"""
    Display = apps.get_model('displays', 'Display')
    
    # Set display_category based on company
    Display.objects.filter(company__isnull=True).update(display_category='standard')
    Display.objects.filter(company__isnull=False).update(display_category='custom')
    
    # Remove "Standard" prefix from standard display names
    standard_displays = Display.objects.filter(display_category='standard')
    for display in standard_displays:
        if display.name.startswith('Standard '):
            display.name = display.name.replace('Standard ', '', 1)
            display.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - add 'Standard' prefix back to standard displays"""
    Display = apps.get_model('displays', 'Display')
    standard_displays = Display.objects.filter(display_category='standard')
    for display in standard_displays:
        if not display.name.startswith('Standard '):
            display.name = f'Standard {display.name}'
            display.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('displays', '0005_update_standard_displays_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='display',
            name='displays_di_company_e4e9b3_idx',
        ),
        migrations.RemoveField(
            model_name='display',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='display',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='display',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='display',
            name='display_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='custom', help_text='Standard displays are available to all companies, custom displays are company-specific', max_length=20),
        ),
        migrations.AlterField(
            model_name='display',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for standard displays, set for custom displays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='accounts.company'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['display_category'], name='displays_di_display_0c9e6c_idx'),
        ),
        migrations.RunPython(set_display_category_and_clean_names, reverse_migration),
    ]
