# Generated by Django 5.2.8 on 2025-11-17 15:32

from django.db import migrations


def cleanup_old_standard_shelves(apps, schema_editor):
    """Delete old standard shelves with generic naming pattern 'Shelf (' to ensure only 6 remain"""
    Display = apps.get_model('displays', 'Display')
    
    # Delete standard shelves with old naming pattern (e.g., "5-Foot Shelf (4 Shelves)")
    Display.objects.filter(
        display_category='standard',
        type='shelf',
        name__contains='Shelf ('
    ).delete()


def reverse_migration(apps, schema_editor):
    """Reverse migration - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0007_refactor_standard_shelves'),
    ]

    operations = [
        migrations.RunPython(cleanup_old_standard_shelves, reverse_migration),
    ]
