# Generated by Django 5.2.8 on 2025-11-17 15:35

from django.db import migrations


def reduce_standard_displays_to_six(apps, schema_editor):
    """Reduce all standard displays to only 6 shelves - remove all other standard display types"""
    Display = apps.get_model('displays', 'Display')
    
    # Keep only these 6 standard shelves
    shelves_to_keep = [
        '5-Foot Wall Mounted Display Shelf',
        '5-Foot Freestanding Storage Shelf',
        '6-Foot Gondola Back Shelf Unit',
        '6-Foot Merchandising Display Shelf',
        '7-Foot Endcap Display Shelf',
        '8-Foot Wall Unit Display Shelf',
    ]
    
    # Delete all standard displays except the 6 shelves we want to keep
    Display.objects.filter(
        display_category='standard'
    ).exclude(
        name__in=shelves_to_keep
    ).delete()


def reverse_migration(apps, schema_editor):
    """Reverse migration - not implemented (would need to restore all deleted standard displays)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0008_cleanup_old_standard_shelves'),
    ]

    operations = [
        migrations.RunPython(reduce_standard_displays_to_six, reverse_migration),
    ]
