# Generated by Django 5.2.8 on 2025-11-18 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('displays', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='summer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width_in', models.DecimalField(decimal_places=2, help_text='Display width in inches', max_digits=10)),
                ('height_in', models.DecimalField(decimal_places=2, help_text='Display height in inches', max_digits=10)),
                ('depth_in', models.DecimalField(blank=True, decimal_places=2, help_text='Display depth in inches', max_digits=10, null=True)),
                ('shelf_count', models.IntegerField(help_text='Number of shelves')),
                ('shelf_spacing', models.DecimalField(blank=True, decimal_places=2, help_text='Shelf spacing in inches', max_digits=10, null=True)),
                ('category_ids', models.JSONField(default=list, help_text='List of selected category IDs')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Stored layout data from frontend', null=True)),
                ('preserve_layout', models.BooleanField(default=False, help_text='If True, use saved layout instead of regenerating')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planograms', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planograms', to=settings.AUTH_USER_MODEL)),
                ('display', models.ForeignKey(blank=True, help_text='Optional reference to display used for dimensions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planograms', to='displays.display')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planograms', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_planograms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
