# Generated by Django 5.2.8 on 2025-12-13 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_and_more"),
        ("displays", "0005_remove_standarddisplay_table"),
        ("planograms", "0001_initial"),
        ("projects", "0002_project_projects_pr_company_703d94_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="planogram",
            index=models.Index(
                fields=["company"], name="planograms__company_2c3267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planogram",
            index=models.Index(
                fields=["project"], name="planograms__project_3b6726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planogram",
            index=models.Index(
                fields=["created_at"], name="planograms__created_b54f55_idx"
            ),
        ),
    ]
