# Generated by Django 5.2.8 on 2025-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='categories',
            field=models.JSONField(default=list, help_text='List of selected category paths'),
        ),
        migrations.AddField(
            model_name='planogram',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='summer', max_length=20),
        ),
    ]
