# Generated by Django 5.2.8 on 2025-12-27 20:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_planogram_defaults(apps, schema_editor):
    """Migrate existing planograms to use default values where fields are null."""
    Planogram = apps.get_model('planograms', 'Planogram')
    Display = apps.get_model('displays', 'Display')

    for planogram in Planogram.objects.all():
        updated = False

        # Set depth_in to default if null
        if planogram.depth_in is None:
            planogram.depth_in = Decimal("24.00")
            updated = True

        # Set shelf_spacing to default if null (prefer display's shelf_spacing if available)
        if planogram.shelf_spacing is None:
            if planogram.display and planogram.display.shelf_spacing:
                planogram.shelf_spacing = planogram.display.shelf_spacing
            else:
                planogram.shelf_spacing = Decimal("12.00")
            updated = True

        # Set layout to empty dict if null
        if planogram.layout is None:
            planogram.layout = {}
            updated = True

        # Auto-select display if null
        if planogram.display is None:
            # Try to get latest custom display for company
            custom_display = Display.objects.filter(
                company=planogram.company,
                display_category='custom'
            ).order_by('-id').first()

            if custom_display:
                planogram.display = custom_display
                updated = True
            else:
                # Fall back to first standard display
                standard_display = Display.objects.filter(
                    display_category='standard'
                ).order_by('id').first()

                if standard_display:
                    planogram.display = standard_display
                    updated = True

        if updated:
            planogram.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration is a no-op since we're just setting defaults."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0005_remove_standarddisplay_table'),
        ('planograms', '0002_planogram_planograms__company_2c3267_idx_and_more'),
    ]

    operations = [
        # Data migration: Update existing records before schema changes
        migrations.RunPython(migrate_planogram_defaults, reverse_migration),
        migrations.RemoveField(
            model_name='planogram',
            name='preserve_layout',
        ),
        migrations.AlterField(
            model_name='planogram',
            name='depth_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.00'), help_text='Display depth in inches', max_digits=10),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='display',
            field=models.ForeignKey(help_text='Reference to display used for dimensions (auto-selected on creation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planograms', to='displays.display'),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='Stored layout data from frontend'),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='shelf_spacing',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Shelf spacing in inches', max_digits=10),
        ),
    ]
