# Generated by Django 5.2.8 on 2025-11-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planograms', '0002_planogram_categories_planogram_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planogram',
            name='categories',
        ),
        migrations.AddField(
            model_name='planogram',
            name='category_ids',
            field=models.JSONField(default=list, help_text='List of selected category IDs'),
        ),
    ]
