# Generated by Django 5.2.8 on 2025-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planograms', '0004_planogram_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='Stored layout data from frontend', null=True),
        ),
    ]
