# Generated by Django 5.2.8 on 2025-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planograms', '0005_planogram_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='preserve_layout',
            field=models.BooleanField(default=False, help_text='If True, use saved layout instead of regenerating'),
        ),
    ]
