# Generated by Django 5.2.8 on 2025-11-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planograms', '0006_planogram_preserve_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planogram',
            name='status',
        ),
    ]
