# Generated by Django 5.2.8 on 2025-12-13 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_and_more"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["company"], name="stores_stor_company_924203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["created_at"], name="stores_stor_created_f1ef67_idx"
            ),
        ),
    ]
